### ISSUE TITLE
Upgrade to Swift 5

### ISSUE THREAD

**Issue by jordanpwood** [Mendeley/mendeleykit#106]
I would like to include a Swift 5 version of Mendeley in my next software release, are you planning on upgrading it and releasing a new cocoa pod?

**Comment by Aaron-Tunney** [comment]
Hi Jordan. I've just open a pull request for Swift 5 compatibility. Hopefully a new version of MendeleyKit will be available by the end of the week.

**Comment by Aaron-Tunney** [comment]
v3.4.2 has now been released, using Swift 5.

**Comment by jordanpwood** [comment]
Thanks!
