### ISSUE TITLE
PDFs: remove PDFs not attached to any citations

### ISSUE THREAD

**Issue by iburunat** [Mendeley/mendeleykit#116]
Hopefully you can solve this PDF-related issue I have, which I haven't found a solution for so far:
How to find PDF in the Mendeley folder that are not attached/assigned/linked to any citation entry (in order e.g., to remove them or create an entry from them)?

Using the `Tidy Up` feature in `Preferences` does not find these PDFs. 

Thanks for your help!

**Comment by vtourraine** [comment]
Thank you for your feedback... but this repo is only for MendeleyKit, the iOS developer library. It seems that your issue is with the desktop client? You should contact the Mendeley support, accessible from the “Help” menu, or directly from the web interface.
