### ISSUE TITLE
Login Failed with message "Credentials are required to access this resource"

### ISSUE THREAD

**Issue by gleery** [Mendeley/mendeleykit#18]
I tried to login in the example project, but it failed. I traced the code and found this error message.
Following your guide at http://dev.mendeley.com/reference/topics/authorization_auth_code.html gives the same response.
It seems to be a server-side problem?
Can you guys help solve this?

**Comment by pweschmidt** [comment]
Hi
in order for the example app to work you will need to have an app registered with dev.mendeley.com
The service is for free. During registration, you will have to provide a redirect URI for the OAuth authentication process, e.g. https://localhost/auth_return
Also when registering, make a note of the client ID and secret generated during registration.

Once you have redirect URI, client ID and client secret, go to the ViewController.h in the example app and set the values for the 3 constants below.
Please, make sure you don't check this back into github - as we don't want to expose client IDs/secrets

#define kMyClientSecret      @"<YOUR CLIENT SECRET>"
#define kMyClientID          @"<YOUR CLIENT ID>"
#define kMyClientRedirectURI @"<YOUR REDIRECT URI>"

I hope this helps
Peter

**Comment by gleery** [comment]
Thanks for your reply.
I've figured out the reason. After I registered my app, I forgot my secret key, so I opened the edit menu, and generate another key. It's OK to pass the first stage, and input my account/password, then it failed with the error message.

I registered another app, use the initial secret key, everything is OK.

**Comment by pweschmidt** [comment]
Thanks for getting back - I am glad it's sorted.
Peter
