### ISSUE TITLE
Is status.mendeley.com deprecated?

### ISSUE THREAD

**Issue by karlbecker** [Mendeley/mendeleykit#21]
Just curious if http://status.mendeley.com is deprecated. It has had a lot of red errors the last few days, and now it currently just says `Unknown error` without any status information whatsoever.  

![mendeley_status_red](https://cloud.githubusercontent.com/assets/1091559/6947007/c0b175ae-d869-11e4-8139-374ff8d0e53c.png)

Sorry if this isn't quite the right place to post this, but a PM from twitter.com/MendeleyAPI in response to (my tweet about the status page)[https://twitter.com/karlbecker_com/status/583266510078005248] said to just check out the API developer site, with no further info... without a dedicated forum on there, I figured this is as close to asking as possible  :)

Thanks for the info!

**Comment by robertknight** [comment]
Hello @karlbecker - The page isn't deprecated and indeed is broken right now. I've asked our QA team to look into it.

The API has had some issues over the past few days but everything should be resolved now. Please let us know if you still encounter any issues.

**Comment by karlbecker** [comment]
Thanks for the quick response, @robertknight ! 

I'll close this issue, since I was just looking for feedback.  Glad to see the API issues (which we were getting some reports from) are taken care of. Look forward to the status page fix!
