### ISSUE TITLE
Include MendeleyKit on the official CocoaPods repo

### ISSUE THREAD

**Issue by karlbecker** [Mendeley/mendeleykit#35]
The README says to include MendeleyKit as a pod into my app by adding this line to my Podfile:
```
pod 'MendeleyKit', :git => 'https://github.com/Mendeley/mendeleykit.git'
```

If I want to use a different version, I cannot specify a version such as
```
pod 'MendeleyKit', '~> 1.1.1', :git => 'https://github.com/Mendeley/mendeleykit.git'
```

If I try that, I get:
```
[!] A dependency with an external source may not specify version requirements (MendeleyKit).
```

I could set a tag in the `git:` value, but then I cannot take advantage of additional 1.1.x improvements - instead, I would be stuck at whatever tag I specify, rather than being able to get enhancements while the 1.1.x line is moving on, thanks to semantic versioning allowing me to be comfortable with 1.1.x improvements to always be compatible with 1.1.1.

This would be the ideal way for me to specify my dependency on MendeleyKit, since I can still get 1.1.x upgrades that are compatible with my use of MendeleyKit, but once the version bumps up to 1.2.x or beyond and breaking changes are introduced, `pod install` won't try to install a newer, broken version of the library into my app.

Because CocoaPods lives outside of the list of pods at `https://cocoapods.org`, I am unable to set my app to use a specific version of the pod.  

Could you please put it up on cocoapods.org?

Thanks!

**Comment by pweschmidt** [comment]
Just cleaning this up. It should be up there now.
