### ISSUE TITLE
Swift 3.0 support

### ISSUE THREAD

**Issue by jordanpwood** [Mendeley/mendeleykit#58]
I am trying out the Xcode 8 beta with an app which uses MendeleyKit, and it doesn't appear to be Swift 2.3 compliant.  Is someone already working on that? If not, I could code up the changes and make a PR; it seems like only simple changes are needed.

**Comment by pweschmidt** [comment]
Hi Jordan
yes, we are going to convert it to Swift 3 to be compatible with XCode 8 (not Swift 2.3). There is already a branch and we will publish it once XCode 8 is officially live

**Comment by jordanpwood** [comment]
Xcode 8 is out, and I see that you're prepping a branch, will you be putting your Swift 3 version into `master` soon?

**Comment by pweschmidt** [comment]
we need to check with other users of the SDK. As Swift 3 is a breaking change it means any users of the SDK would have to build using XCode8 - not everyone maybe ready yet.
In the meantime, master has been merged back into the iOS10_Ready branch. So anyone wanting to use that branch for their builds should use that

**Comment by pweschmidt** [comment]
Just to let you now: we are getting ready for an update to Swift3 in  the Kit very shortly

**Comment by jordanpwood** [comment]
Great!  Thanks.

**Comment by jordanpwood** [comment]
My team has recently noticed that the `iOS10_Ready` branch to this repo has disappeared, but the master branch doesn't appear to have been updated to Swift 3 yet.  Where do I go for Swift 3 support currently, @pweschmidt?

**Comment by pweschmidt** [comment]
Hiya
the Development branch should be upgraded to XCode8/Swift 3 - so you can try that (the iOS10_REady branch was merged with that)
We will be merging the Development with master sometime next week.
Peter

**Comment by pweschmidt** [comment]
Will all be merged and upgraded on master today
