### ISSUE TITLE
Minimum deployment version for iOS is higher than needed?

### ISSUE THREAD

**Issue by jordanpwood** [Mendeley/mendeleykit#61]
The minimum deployment target defined in `MendeleyKitiOS.podspec`is set to 9.1.  I've been using the development branch that I believe this release was based on with iOS 8 with no problems that I know of.  Is there a reason you increased the deployment target?  

My company is in the situation where our users are the clients of our customers, and we get a lot of pushback when we increase our deployment target.  We still have a couple hundred users on iOS versions which are lower than 9.1.  Could you decrease the target?

**Comment by pweschmidt** [comment]
Hi Jordan
I will roll it back to iOS8 then

**Comment by pweschmidt** [comment]
MendeleyKit 3.0.1 has min version set to 8.1
