### ISSUE TITLE
Allow cocoapods users to choose which version of the MendeleyKitiOS pod to use

### ISSUE THREAD

**Issue by jordanpwood** [Mendeley/mendeleykit#79]
The instructions in on the readme page say that the following should be used to pull Mendeley's iOS framework:

`pod 'MendeleyKitiOS', :git => 'https://github.com/Mendeley/mendeleykit.git'
`

However, doing it this way doesn't allow for the cocoapod user to choose which version of pod to get.  If you either [published to the Cocoapod central repository](https://guides.cocoapods.org/making/making-a-cocoapod.html), or used their instructions on making a [private pod](https://guides.cocoapods.org/making/private-cocoapods), then users like me could use cocoapod's versioning system. Normally a framework made for public consumption would be published to cocoapods master repo.  However, if you want to keep the pods solely in your GitHub repositiory, then you could create a private pod. I maintain a private pod for my company, and I have found that it works quite well with versioning.

The fact that this cocoapod doesn't support versions made it particularly tricky for me to use it during the Swift 2 to 3 upgrade period, and it is making it difficult for me to debug a problem my app is currently having logging into Mendeley.

**Comment by Aaron-Tunney** [comment]
Sorry for the delay in responding to this request.

We've published the latest release (3.2.2) to the cocoapod central repository so users won't have to specify the git path in future. 

Unfortunately, we've had changes to the SDK to get it working with the central repository. That means that there isn't an easy way to publish older podspecs. You'll have to rely on the 'commit' option to roll back to older versions for now.

**Comment by jordanpwood** [comment]
Thank you!
