### ISSUE TITLE
Our app is no longer able to log users in to Mendeley

### ISSUE THREAD

**Issue by jordanpwood** [Mendeley/mendeleykit#80]
We have had Mendeley integration in our app for a while, and it has been working up until recently.  I have 2 versions of my app, the one in the store that was compiled with Xcode 8, and a release candidate that I will be releasing in the next few days that was compiled with Xcode 9.  The older version shows a Mendeley login screen with a red background.  This login works on iOS 9 and 10, but not iOS 11.  My release candidate shows a grey login page which appears to be the same as is used in the Mendeley app.  I cannot get this page to work on any OS.  After the credentials are entered and the user hits the login button, nothing happens.  I have put breakpoints in the web kit delegate methods in `MendeleyLoginWebLKitHandler`, but none of them get hit.

Is there anything else I can do to get this working?  Has there been a change on the server which we are communicating with?

**Comment by Aaron-Tunney** [comment]
Hi Jordan,

That's interesting to hear. We've not encountered this problem with the official Mendeley app or had any other reports of this issue. Unless there's a problem with your client ID, I'd be surprised if it's a server-side issue.

Would it be possible for you to send us a sample project so that we can investigate this issue further? My e-mail address is a.tunney@elsevier.com .

Thanks, Aaron

**Comment by karlbecker** [comment]
Hi @Aaron-Tunney ,

I'm @jordanpwood 's teammate, andI just logged into our account on dev.mendeley.com and I see no issues with our client IDs.  Where would I look for an issue?

Thanks, Karl

**Comment by jordanpwood** [comment]
I have tried running the example app included in your repo, using the `MendeleyKitExample` target.  I replaced the secret, client ID, and redirect URI with the values from our app.  I know the URI won't work in this app as is, since it uses a custom scheme.  It is `browzine://mendeley`.  However, my understanding is that one of the methods in `MendeleyLoginWebKitHandler` should be called before we try redirecting to that URI.  I have a breakpoint in every method in that class, and nothing is getting called after `configureWebView`.  Is there something else I would have to setup to make the example app work?

I can send you our ID and secret if I need to.

**Comment by Aaron-Tunney** [comment]
@karlbecker, @jordanpwood - If you could send me over your client ID, I can check with the server side guys to see if there's a problem with it.

You're correct that debugger should stop in webView(_ webView: WKWebView, didReceiveServerRedirectForProvisionalNavigation navigation: WKNavigation!) once the user taps on Sign In. 

I'll run the example app today with our client ID and secret. I'll let you know what I discover.

**Comment by Aaron-Tunney** [comment]
I've tested login using the example app, our client ID/secret and Xcode 9.1.

The breakpoint in webView(_ webView: WKWebView, didReceiveServerRedirectForProvisionalNavigation navigation: WKNavigation!) is successfully hit after tapping on the Sign In button and the successful login dialog is shown.

You could try setting the redirect URI to http://localhost/auth_return but you may get an error that the redirect doesn't match the one registered for your application. Let me know your client ID and I'll talk to our server-side team.

**Comment by jordanpwood** [comment]
Our ID is 1024.  I think the issue is that something is choking on our redirect URL.  I tried creating two new client IDs, one using the `browzine://mendeley` URL and one using `http://localhost/auth_return`.  The first new ID showed the same problems as our production ID, and the second worked just fine.

**Comment by Aaron-Tunney** [comment]
@karlbecker, @jordanpwood - I'm still not entirely sure what's going on but I agree that the redirect appears to be causing the problem.

If you implement the delegate method webView(_ webView: WKWebView, didFailProvisionalNavigation navigation: WKNavigation!, withError error: Error) in MendeleyLoginWebKitHandler, does a breakpoint in there get hit and, if so, what's the error?

**Comment by jordanpwood** [comment]
I have verified that using a new client ID with `http://localhost/auth_return` as the redirect URI in our regular app does make it so we can log people in.  I can change to a new client ID, but that doesn't fix existing versions of the app.

**Comment by vtourraine** [comment]
@jordanpwood @karlbecker Hello ; I was experiencing the same issue. The good news is that I’ve found a solution for devices running iOS 11, the bad news is that this is still an issue for iOS 9 and iOS 10.

See #85

**Comment by vtourraine** [comment]
@jordanpwood @karlbecker Hello again ; it looks like we have now fixed this bug for iOS 9/10/11. Could you try this update, and see if that solves the issue for your app?
